site_name: Kelvin's Profile

repo_url: https://github.com/hoishing.github.io
extra_css:
  - stylesheets/extra.css

theme:
  name: "material"
  font:
    text: Varela Round
  icon:
    repo: fontawesome/brands/github
  favicon: assets/rocket-launch.svg
  logo: assets/rocket-launch.svg
  palette:
    # Palette toggle for dark mode
    - primary: light blue
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

    # Palette toggle for light mode
    - primary: light blue
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

  features:
    - navigation.instant
    # - navigation.tracking
    # - navigation.expand
    # - toc.integrate

plugins:
  - social
  - search:
      lang: en
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_signature_annotations: true

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - toc:
      toc_depth: 3

nav:
  - Overview: index.md
  - Mobile Apps:
    - ZERO: proj/zero-game.md
    - Video Compressor ↗: https://apps.apple.com/hk/app/video-compressor/id482465886
    - Easy Dictionary ↗: https://apps.apple.com/hk/app/%E8%8B%B1%E6%BC%A2%E5%AD%97%E5%85%B8-easy-dictionary/id684273271
    - 英漢字典 ↗: https://apps.apple.com/hk/app/%E8%8B%B1%E6%BC%A2%E5%AD%97%E5%85%B8-ec-dict/id371152394
    - 同音字典 ↗: https://apps.apple.com/hk/app/%E5%90%8C%E9%9F%B3%E5%AD%97%E5%85%B8/id956045098
  - Web Apps:
    - Speech Recognition: proj/speech-recog.md
  - Chrome Extensions:
    - Mini Authenticator: proj/mini-authenticator.md
    - Multilingual Voice Search: proj/multilingual-voice-search.md
    - Chrome ext creation template: proj/template-chrome-ext.md
  - Python Packages:
    - pypable: proj/pipable.md
    - kTemplate: proj/ktemplate.md
  - NPM Packages:
    - TOTP Generator: proj/totp-auth.md
  - Utilities:
    - Icon Resize CLI: proj/icon-resize-cli.md
    - CangJie IME: proj/cangjie.md
    - Selenium Crawler: proj/selenium-crawler.md
    - Google Playbook Annotations to MD: proj/playbook2md.md
    - Raycast Scripts: proj/raycast-scripts.md
  - Legacy Projects:
    - Atom Cell Navigation: proj/cell-navigation.md
    - Markdown to Dash Docset: proj/md2html_dash.md
    - GData iOS Static lib: proj/gdata-static-lib.md
    - 認識佛教 iOS Apps: proj/buddhism-objc.md
    - Ruby Static Site Generator: proj/ruby-SSG.md
  - Blog:
    - Auto Format Svelte In Vscode: blog/2020-12-14-auto-format-svelte-in-vscode.md
    - 打造你專屬的倉頡輸入法: blog/2020-10-27-cangjie.md
    - Using Chinese Characters in Matplotlib: blog/2019-04-21-Using Chinese Characters in Matplotlib.md
    - Using Javascript with WKWebView: blog/2017-12-29-Using Javascript with WKWebView.md
    - Adding Login Items for macOS: blog/2017-12-15-Adding Login Items for macOS.md
    - Create Menu Bar Apps On macOS: blog/2017-10-10-Create Menu Bar Apps On macOS.md
    - Providing Services On macOS: blog/2017-08-12-Providing Services On macOS.md
