site_name: Kelvin's Profile

site_url: https://hoishing.github.io
repo_url: https://github.com/hoishing
extra_css:
  - stylesheets/extra.css

theme:
  name: "material"
  custom_dir: overrides
  font:
    text: Varela Round
  icon:
    repo: fontawesome/brands/github
  favicon: assets/favicon.png
  logo: assets/rocket-launch.svg
  palette:
    # Palette toggle for dark mode
    - primary: light blue
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

    # Palette toggle for light mode
    - primary: light blue
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

  features:
    - navigation.instant
    - toc.integrate
    # - navigation.footer
    # - navigation.tracking
    # - navigation.expand

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/hoishing
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/hoishing
    - icon: fontawesome/brands/github
      link: https://github.com/hoishing
    - icon: fontawesome/brands/dev
      link: https://dev.to/hoishing

plugins:
  - social
  - search:
      lang: en
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_signature_annotations: true

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - toc:
      toc_depth: 3

nav:
  - index.md
