[tool.poetry]
name = "hoishing-github-io"
version = "0.1.0"
description = ""
authors = ["Kelvin Ng <hoishing@gmail.com>"]
readme = "README.md"
packages = [{include = "hoishing"}]

[tool.poetry.dependencies]
python = "^3.11"
mkdocs-material = "^9.1.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
