[project]
name = "hoishing-github-io"
version = "0.1.0"
description = "Kelvin's personal website built with MkDocs"
authors = [{ name = "Kelvin Ng", email = "hoishing@gmail.com" }]
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["mkdocs-material[imaging]", "mkdocstrings[python]"]
