[tool.poetry]
name = "hoishing-github-io"
version = "0.1.0"
description = "Kelvin's Personal Website"
authors = ["Kelvin Ng <hoishing@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
toml = "^0.10.2"
mkdocs-material = "^9.0.11"
click = "^8.1.3"
coverage = "^7.1.0"
pytest = "^7.2.1"
genbadge = { extras = ["coverage"], version = "^1.1.0" }
mkdocstrings = { extras = ["python"], version = "^0.20.0" }
pillow = "^9.4.0"
cairosvg = "^2.6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
